name: Periodic health check ping

# NOTE: Disabled to prevent consumption of GitHub Action hours, using Git push as the workflow trigger
on:
  schedule:
    - cron: '*/10 * * * * *'

# on:
#  push:
#   branches:
#    - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v4
      with:
        url: ${{ secrets.WEB_SERVICE_URL }}